# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='auther_id',
            new_name='auther',
        ),
    ]
