# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 02:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190329_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='postdate',
        ),
    ]
