# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cm_state',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('men_percent', models.IntegerField(max_length=11)),
                ('cpu_percent', models.IntegerField(max_length=11)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'cm_state',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partition', models.CharField(max_length=45)),
                ('size', models.BigIntegerField(max_length=45)),
                ('deleted', models.IntegerField(max_length=1)),
            ],
            options={
                'db_table': 'disk',
            },
        ),
        migrations.CreateModel(
            name='Disk_state',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size_percent', models.IntegerField(max_length=11)),
                ('date', models.DateTimeField()),
                ('disk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='show.Disk')),
            ],
            options={
                'db_table': 'disk_state',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=45)),
                ('ip', models.CharField(max_length=45, unique=True)),
                ('cpu_num', models.IntegerField(max_length=11)),
                ('men_size', models.BigIntegerField(max_length=20)),
                ('disk_size_total', models.BigIntegerField(max_length=20)),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.AddField(
            model_name='disk',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Host'),
        ),
        migrations.AddField(
            model_name='cm_state',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Host'),
        ),
    ]
